name: csc_picker
description: A flutter package to display list of Countries, States and Cities depends on Selected, also you can search country, state, and city all around the world.
version: 0.2.7
homepage: https://github.com/altafc22/csc_picker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  skeletonizer: ^1.0.1
  string_similarity: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  flutter_lints: ^3.0.1

flutter:
  assets:
    - lib/assets/
